### ISSUE TITLE
Bar keeps growing if value goes > 1.0

### ISSUE THREAD

**Issue by lambdaupb** [Ralith/yapb#1]
https://github.com/Ralith/yapb/blob/master/src/lib.rs#L75

should probably clamp the value to 1.0.

Values of > 1.0 can appear if the original total was an estimation or user supplied.
This will lead to percentages > 100% making at least some sense.

**Comment by Ralith** [comment]
Good thought. Fixed in 06040141d9e293b49e6ec8a307146d5801e5a98a.
